[package]
name = "doodle"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
tokio = { version = "*", features = ["full"] }
tower = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "1.0.145"
mongodb = "3.3.0"
futures = "0.3.31"
dotenv = "0.15.0"
